[Revertme] Remove currently unsupported SysUiStatsLog code.
Revert "Update SysUiStatsLog.write with received_latency_millis"

This reverts commit 6824aed168717e726cec5bcc70af8e10138aaae4.

Revert "Populate additional fields for smartspace logging"

This reverts commit c5daad2afb3569c3d23008b45b1c5196053e3e1b.

---

We are currently missing updates in SysUiStatsLog in com.google.android.os.statsd

This should be adressed soon..

For now let's avoid those errors:

frameworks/base/packages/SystemUI/src/com/android/systemui/media/MediaCarouselController.kt:775:17: error: type mismatch: inferred type is Int but Float was expected
                interactedSubcardCardinality,
                ^
frameworks/base/packages/SystemUI/src/com/android/systemui/media/MediaCarouselController.kt:776:17: error: the integer literal does not conform to the expected type String!
                0 // received_latency_millis
                ^
frameworks/base/packages/SystemUI/src/com/android/systemui/media/MediaCarouselController.kt:762:17: error: too many arguments for public open fun write(code: Int, arg1: Int): U
nit defined in com.android.systemui.shared.system.SysUiStatsLog
                instanceId,
                ^
frameworks/base/packages/SystemUI/src/com/android/systemui/media/MediaCarouselController.kt:765:17: error: too many arguments for public open fun write(code: Int, arg1: Int): U
nit defined in com.android.systemui.shared.system.SysUiStatsLog
                SysUiStatsLog.SMART_SPACE_CARD_REPORTED__CARD_TYPE__UNKNOWN_CARD,
                ^